name: Build test

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.19.1
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run site
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: cpany
      - uses: actions/checkout@v2
        with:
          path: ./.main
      - uses: ./.main
        name: Fetch Data
