name: Build test

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"
        
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
          
      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: pnpm

      - run: pnpm install

      - run: |
          pnpm run build
          pnpm link packages/cli

      - name: Export CPany Page Image
        run: npx cpany export ./example

      - name: Upload CPany Page Image
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png

      - name: Build
        run: npx cpany build example --base /CPany/
        env:
          DEBUG: 'cpany:*'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: pnpm

      - name: Build CPany
        run: |
          pnpm install
          pnpm build
          pnpm link packages/cli

      - uses: actions/checkout@v2
        with:
          ref: cpany
          path: .cpany

      - name: Fetch Data
        run: npx cpany fetch ./.cpany/ --plugin codeforces hdu
