name: Build test

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.23.2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - name: Export CPany Page Image
        run: pnpx cpany export ./example
      - name: Upload CPany Page Image
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png
      - name: Build
        run: pnpx cpany build example --base /CPany/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.23.2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: pnpm
      - name: Build CPany
        run: |
          pnpm install
          pnpm build
      - uses: actions/checkout@v2
        with:
          ref: cpany
          path: .cpany
      - name: Fetch Data
        run: pnpx cpany fetch ./.cpany/ --plugin codeforces hdu
