name: Fetch data

on:
  workflow_dispatch:
  push:
    branches:
      - cpany

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: pnpm/action-setup@v2
        with:
          version: 6.23.2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: pnpm
      - name: Build CPany
        run: |
          pnpm install
          pnpm build
      - uses: actions/checkout@v2
        with:
          path: .cpany
      - name: Fetch Data
        run: pnpx cpany fetch ./.cpany/ --plugin codeforces hdu
      - name: Push
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Fetch data on $FETCH_TIME"
          git push
        working-directory: ./.cpany/
